### ISSUE TITLE
injection error + silent crash in ios

### ISSUE THREAD

**Issue by MPMaker** [YoYoGames/GMEXT-GoogleSignIn#1]
If you look at the extension's iOS injection, there is code like this:

>      pod 'GoogleSignIn','6.2.4

Quotation marks are missing.
This will cause an error, and if you replace ,'6.2.4 to ,'6.2.4' the error will not occur.

But even if I edit this part,
when you call Google Sign In on iOS, the game ends without an error message.

**Comment by DiasFranciscoA** [comment]
Updated extension please remove the old one completly and import the new version.
This version has some small breaking changes please refer to the documentation for more information.
